In [1]:
import numpy as np

In [2]:
array1 = np.zeros(5)
array1

array([0., 0., 0., 0., 0.])

In [4]:
array2 = np.zeros((3, 4), dtype=int)
array2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
array3 = np.ones(4, dtype=str)
array3

array(['1', '1', '1', '1'], dtype='<U1')

In [8]:
array4 = np.full((6, 2), 17)
array4

array([[17, 17],
       [17, 17],
       [17, 17],
       [17, 17],
       [17, 17],
       [17, 17]])

In [10]:
array5 = np.arange(1, 11, 3)
array5

array([ 1,  4,  7, 10])

In [28]:
array6 = np.linspace(1, 27, 6)
array6

array([ 1. ,  6.2, 11.4, 16.6, 21.8, 27. ])

In [31]:
array7 = array6.reshape(3, 2)
array7

array([[ 1. ,  6.2],
       [11.4, 16.6],
       [21.8, 27. ]])